name: "Build and cache nix packages"
on:
  push: 
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  build-and-cache-nix-packages:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v14
        with:
          name: holochain-ci

      - uses: cachix/cachix-action@v14
        with:
          name: holochain-open-dev

      - uses: cachix/cachix-action@v14
        with:
          name: darksoil-studio

      - name: Install and test
        run: |
          nix develop --no-update-lock-file --accept-flake-config --command bash -c "pnpm i && pnpm t && pnpm -F @darksoil-studio/roles build"

      - name: Build debug zomes
        env:
          CACHIX_AUTH_TOKEN: "${{ secrets.DARKSOIL_CACHIX_AUTH_TOKEN }}"
        run: |
          cachix watch-exec darksoil-studio -- nix build --no-update-lock-file --accept-flake-config -L .#roles_integrity
          cachix push darksoil-studio $(nix path-info --json --accept-flake-config --no-warn-dirty .#roles_integrity | nix run nixpkgs#jq -- -r '.[].path')
          cachix pin darksoil-studio roles_integrity_debug $(nix path-info --json --accept-flake-config --no-warn-dirty .#roles_integrity | nix run nixpkgs#jq -- -r '.[].path')

          cachix watch-exec darksoil-studio -- nix build --no-update-lock-file --accept-flake-config -L .#roles
          cachix push darksoil-studio $(nix path-info --json --accept-flake-config --no-warn-dirty .#roles | nix run nixpkgs#jq -- -r '.[].path')
          cachix pin darksoil-studio roles_debug $(nix path-info --json --accept-flake-config --no-warn-dirty .#roles | nix run nixpkgs#jq -- -r '.[].path')

      - name: Build release zomes
        if: matrix.os == 'ubuntu-latest'
        env:
          CACHIX_AUTH_TOKEN: "${{ secrets.DARKSOIL_CACHIX_AUTH_TOKEN }}"
        run: |
          cachix watch-exec darksoil-studio -- nix build --no-update-lock-file --accept-flake-config -L .#roles_integrity.meta.release
          cachix push darksoil-studio $(nix path-info --json --accept-flake-config --no-warn-dirty .#roles_integrity.meta.release | nix run nixpkgs#jq -- -r '.[].path')
          cachix pin darksoil-studio roles_integrity $(nix path-info --json --accept-flake-config --no-warn-dirty .#roles_integrity.meta.release | nix run nixpkgs#jq -- -r '.[].path')

          cachix watch-exec darksoil-studio -- nix build --no-update-lock-file --accept-flake-config -L .#roles.meta.release
          cachix push darksoil-studio $(nix path-info --json --accept-flake-config --no-warn-dirty .#roles.meta.release | nix run nixpkgs#jq -- -r '.[].path')
          cachix pin darksoil-studio roles $(nix path-info --json --accept-flake-config --no-warn-dirty .#roles.meta.release | nix run nixpkgs#jq -- -r '.[].path')
