name: "Build and cache nix packages"
on:
  push: 
    branches: [ main ]

jobs:
  testbuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v14
        with:
          name: holochain-ci

      - uses: cachix/cachix-action@v14
        with:
          name: holochain-open-dev

      - name: Install and test
        run: |
          nix develop --command bash -c "pnpm i && pnpm t && pnpm -F @darksoil-studio/roles build"

      - name: Build zomes
        env:
          CACHIX_AUTH_TOKEN: "$"
        run: |
          nix build -L .#roles_integrity
          cachix push holochain-open-dev $(nix path-info --accept-flake-config .#roles_integrity)
          cachix pin holochain-open-dev roles_integrity_debug $(nix path-info --accept-flake-config .#roles_integrity)

          nix build -L .#roles_integrity.meta.release
          cachix push holochain-open-dev $(nix path-info --accept-flake-config .#roles_integrity)
          cachix pin holochain-open-dev roles_integrity $(nix path-info --accept-flake-config .#roles_integrity.meta.release)

          nix build -L .#roles
          cachix push holochain-open-dev $(nix path-info --accept-flake-config .#roles)
          cachix pin holochain-open-dev roles_debug $(nix path-info --accept-flake-config .#roles)

          nix build -L .#roles.meta.release
          cachix push holochain-open-dev $(nix path-info --accept-flake-config .#roles.meta.release)
          cachix pin holochain-open-dev roles $(nix path-info --accept-flake-config .#roles.meta.release)
